year: "2024"
theme: ocean
organizers:
- 中央研究院資訊科學研究所
- 國立臺灣大學資訊管理學系
sponsors:
- 入山山有限公司
- 國立臺灣大學資訊工程學系
- 國立臺灣大學電機工程學系
programme:
- 柯向上
- 陳亮廷
- 穆信成
local:
- 林柏芬
- 韓愷真
ta_boss: 蔡子濬
ta:
- 林秉軒
- 陳正康
- 曾顯恩
- 蔡柏毅
- 薛盛安
- 張耀晟
date: "7/1-7/12"
time: "09:00-17:00"
